# Loading mesh to tensor

This example shows usage of 3D object - tensor interface. It can be used to load both *.stl* and *.obj* files and convert them into pytorch tensors.

In [1]:
import sys
import os
import torch
import trimesh

module_path = os.path.abspath(os.path.join('..', 'object-tensor-interface'))
sys.path.append(module_path)
from trimesh_utils import load_to_tensor, Mesh_Tensor

## Mesh tensor generation

Mesh_Tensor class is a member of trimesh_utils package. It has methods to get different tensors for different needs:

- .get_mesh(): output is a trimesh mesh structure. Easy to visualise and process, it's NOT a tensor!
- .get_faces(): output is a tensor consisting of faces. Each face is a list of vertex IDs - so for example first face is [0, 1, 2]. It means that this face has three corners - three elements of vertices tensor with index 0, 1 and 2. It has information about wich corners are in which face, it doesn't have any dimensions here, more like mesh organization.
- .get_vortices(): output is a tensor consisting of vertices location. Every element of this tensor is a list of three dimensions: x, y and z parameters of a single vortex.
- .get_corners(): output is a tensor consisting of triangles. Each element of the tensor is a list of vortices, and every vortex is a list of x, y and z params. Structure of this tensor is almost like *.stl* file structure, but without normal vector. Basically a list of all corner coordinates, grouped by the face they create.
- .get_path(): returns a path to object, just in case
- .get_centers(): returns a tensor consisting of geometric centers of faces. Each element is a list of x, y and z coordinates of a center.
- .get_normals(): returns a tensor consisting of normal vectors of each face.
- .get_edges(): returns a tensor consisting of edges. Every edge is a list of two IDs - those are vetrices ID, which means you can index vortices tensor with them to get their coordinates. It doesn't contain any details about length or anything like that, just indexing.

In [2]:
mesh = Mesh_Tensor('Eiffel_Tower.stl') #Eiffel Tower from https://ozeki.hu/p_1116-sample-stl-files-you-can-use-for-testing.html
mesh.get_mesh().show()

In [3]:
mesh.get_faces()

tensor([[    0,     1,     2],
        [    2,     1,     3],
        [    4,     5,     6],
        ...,
        [  398,   396, 24274],
        [24274,   396,   394],
        [24274,   394, 24268]])

In [4]:
mesh.get_vertices()

tensor([[-15.0174,   5.4680,  24.8882],
        [-15.0174,   3.8432,  24.8882],
        [-14.7797,   5.4680,  24.8882],
        ...,
        [ -1.4861,  -1.4861,  74.8665],
        [ -0.8804,  -0.8804,  99.9018],
        [ -0.8601,  -0.8601, 102.9952]])

In [6]:
mesh.get_path()

'Eiffel_Tower.stl'

In [7]:
mesh.get_centers()

tensor([[-14.9382,   4.9264,  24.8882],
        [-14.8590,   4.3848,  24.8882],
        [ -6.8434,   0.6734,  24.8882],
        ...,
        [  0.1191, -15.2452,  23.0833],
        [  0.1191, -15.2853,  23.1124],
        [  0.1191, -15.3650,  23.1534]])

In [8]:
mesh.get_corners()

tensor([[[-15.0174,   5.4680,  24.8882],
         [-15.0174,   3.8432,  24.8882],
         [-14.7797,   5.4680,  24.8882]],

        [[-14.7797,   5.4680,  24.8882],
         [-15.0174,   3.8432,  24.8882],
         [-14.7797,   3.8432,  24.8882]],

        [[ -6.7642,   0.1188,  24.8882],
         [ -6.7642,   1.7824,  24.8882],
         [ -7.0019,   0.1188,  24.8882]],

        ...,

        [[  0.1191, -15.2332,  23.2764],
         [  0.1191, -15.2968,  23.3154],
         [  0.1191, -15.2056,  22.6580]],

        [[  0.1191, -15.2056,  22.6580],
         [  0.1191, -15.2968,  23.3154],
         [  0.1191, -15.3535,  23.3638]],

        [[  0.1191, -15.2056,  22.6580],
         [  0.1191, -15.3535,  23.3638],
         [  0.1191, -15.5359,  23.4385]]])

In [9]:
mesh.get_normals()

/home/ppjotrek/Python/Medshapenet/object-tensor-interface/trimesh_utils.py:73: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:206.)
  return torch.from_numpy(normals).float()


tensor([[0.0000e+00, 0.0000e+00, 1.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.0000e+00],
        ...,
        [1.0000e+00, 8.5003e-08, 1.3874e-07],
        [1.0000e+00, 1.2298e-07, 1.4401e-07],
        [1.0000e+00, 5.2959e-08, 1.2933e-07]])

In [10]:
mesh.get_edges()

tensor([[    0,     1],
        [    0,     2],
        [    1,     2],
        ...,
        [47972, 56419],
        [47984, 56419],
        [56401, 56419]])